spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        # 手动ack
        acknowledge-mode: manual
        prefetch: 2