spring:
  rabbitmq:
    # 单机的写法
    host: localhost
    port: 5672
    # 集群的写法
#    addresses: localhost:5672,localhost:5673,localhost:5674
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        # 手动ack
        acknowledge-mode: manual
        prefetch: 2
    # 确认回调
    publisher-confirm-type: correlated
    # 入队失败回调
    publisher-returns: true